name: an_console
description: A developer can fully customize the console content, which can be used to display logs on the UI, serve as an app configuration center, and more functionalities.
version: 0.4.1
homepage: https://github.com/aymtools/an_console/
issue_tracker: https://github.com/aymtools/an_console/issues
topics:
  - console
  - vconsole
  - fconsole
  - configuration

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  shared_preferences: ^2.2.1
  collection: ^1.16.0
  path: ^1.9.0

  linked_scroll_controller: ^0.2.0

dev_dependencies:
  flutter_lints: ^5.0.0

flutter: