name: an_console
description: A developer can fully customize the console content, which can be used to display logs on the UI, serve as an app configuration center, and more functionalities.
version: 1.2.1
homepage: https://github.com/aymtools/an_console/
issue_tracker: https://github.com/aymtools/an_console/issues
topics:
  - console
  - vconsole
  - fconsole
  - configuration

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter

  intl: ">=0.17.0 <1.0.0" # 允许从 0.17.0 开始的所有 0.x 版本
  shared_preferences: ^2.2.1
  collection: ^1.16.0
  path: ^1.8.3

  linked_scroll_controller: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter: