name: an_console
description: A new Flutter project.
version: 1.0.0
homepage: https://github.com/aymtools/an_console/

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  linked_scroll_controller: ^0.2.0
  shared_preferences: ^2.0.10


flutter: